Update ios.yml

diff --git a/.github/workflows/ios.yml b/.github/workflows/ios.yml
--- a/.github/workflows/ios.yml
+++ b/.github/workflows/ios.yml
@@ -9,68 +9,32 @@ on:
     branches: [main]
 
 jobs:
-  build_with_signing:
+  deploy:
     runs-on: macos-latest
     steps:
-      # this was more debug as was curious what came pre-installed
-      # GitHub shares this online, e.g. https://github.com/actions/runner-images/blob/macOS-12/20230224.1/images/macos/macos-12-Readme.md
-      - name: check Xcode version
-        run: /usr/bin/xcodebuild -version
+      - uses: actions/checkout@v3
 
-      - name: checkout repository
-        uses: actions/checkout@v3
-
-      - name: Install the Apple certificate and provisioning profile
-        env:
-          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
-          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
-          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
-          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
-        run: |
-          # create variables
-          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
-          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
-          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
-
-          # import certificate and provisioning profile from secrets
-          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
-          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH
-
-          # create temporary keychain
-          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
-          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
-          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
-
-          # import certificate to keychain
-          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
-          security list-keychain -d user -s $KEYCHAIN_PATH
-
-          # apply provisioning profile
-          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
-          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles          
-
-      - name: build archive
-        run: |
-          xcodebuild -scheme "MovieDBList" \
-          -archivePath $RUNNER_TEMP/MovieDBListInfo.xcarchive \
-          -sdk iphoneos \
-          -configuration Debug \
-          -destination generic/platform=iOS \
-          clean archive          
-
-      - name: export ipa
-        env:
-          EXPORT_OPTIONS_PLIST: ${{ secrets.EXPORT_OPTIONS_PLIST }}
-        run: |
-          EXPORT_OPTS_PATH=$RUNNER_TEMP/ExportOptions.plist
-          echo -n "$EXPORT_OPTIONS_PLIST" | base64 --decode -o $EXPORT_OPTS_PATH
-          xcodebuild -exportArchive -archivePath $RUNNER_TEMP/MovieDBListInfo.xcarchive -exportOptionsPlist $EXPORT_OPTS_PATH -exportPath $RUNNER_TEMP/build          
-
-      - name: Upload application
-        uses: actions/upload-artifact@v3
+      - name: Set up ruby env
+        uses: ruby/setup-ruby@v1.138.0
         with:
-          name: app
-          path: ${{ runner.temp }}/build
-          # you can also archive the entire a specific part
-          # /build/MovieDBList.ipa
-          retention-days: 3
+          ruby-version: 3.2.1
+          bundler-cache: true
+
+      - name: install dependencies
+        run: |
+          gem install bundler
+          cd MovieDBList
+          bundle install
+
+      - name: Check if the encrypted provisioning profile exists
+        run: ls -la ./
+         
+      - name: Decrypt provisioning profile
+        run: |
+          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
+          openssl aes-256-cbc -d -k "secret" -in profile.mobileprovision.enc -out profile.mobileprovision || echo "Decryption failed"
+          mv profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/ || echo "Move operation failed"
+
+      - name: Set Xcode version
+        run: |
+         sudo xcode-select -s /Applications/Xcode_15.0.1.app/Contents/Developer
